### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BachoSeven** [drincoxyz/pinentry-dmenu#1]
Hi, I tried this from the AUR package; my use case is that I use `pass` to unlock my email accounts with `mbsync`; the output I get is `gpg: decryption failed: No secret key`

**Comment by inco-cc** [comment]
have you made `/usr/bin/pinentry-dmenu` the default pinentry program in `~/.gnupg/gpg-agent.conf`? gpg-agent probably won't use it unless explicitly told to, especially with the standard pinentry programs like `pinentry-curses`, `pinentry-gtk-2` etc

is your dmenu build using the [password](https://tools.suckless.org/dmenu/patches/password/) patch? keep in mind this doesn't compile dmenu like [this package](https://aur.archlinux.org/packages/pinentry-dmenu) does, but instead uses the first dmenu binary it can find from $PATH. either way, dmenu must have this patch to mask the passphrase as the user types it

**Comment by BachoSeven** [comment]
I have set `pinentry-program /usr/bin/pinentry-dmenu` in my gpg-agent.conf; and my dmenu is patched with `-P` password support

**Comment by BachoSeven** [comment]
To be clear:
- when I use `pass`, `pinentry-dmenu` is being called;
- however, once I type the password correctly, I get the aforementioned error when trying to use the gpg key

**Comment by inco-cc** [comment]
hmm, I presume `pass` is a shell script?

the only other thing I could think of is maybe you haven't restarted gpg-agent yet to reflect the change in `~/.gnupg/gpg-agent.conf` (with something like `gpgconf --reload gpg-agent`), but if you're seeing dmenu with the `gpg-agent` prompt then this probably isn't the case

check out this script I made called [yankpass](https://github.com/drincoxyz/pinentry-dmenu/files/4909873/yankpass.txt), it acts as a sort of password manager - it prompts the user with dmenu to pick an encrypted password file from `$XDG_DATA_HOME/yankpass/*.gpg`. then it uses `gpg -qd` on the password file, which brings up dmenu with the `gpg-agent` prompt with the masked input field. after entering the password for the gpg key used to encrypt the file, the decrypted password is copied to the clipboard for 10 seconds, with a notification (with dunst on my machine)

perhaps take a look at the script and maybe even see if it works on your machine. if it doesn't, then I suspect something might be up with your gpg setup, since i'm also using the AUR package and it's working as expected

**Comment by BachoSeven** [comment]
No, [pass](https://www.passwordstore.org/) is a password manager which uses gpg; it's also in the [wiki](https://wiki.archlinux.org/index.php/Pass).

I did reboot my machine so gpg-agent should have reloaded. Thanks for the script, I will give it a try and see if there is some other issue at play.

**Comment by BachoSeven** [comment]
Even with `yankpass`, the behaviour is the same, namely that gpg seem to be hanging for around a minute or so; and then fails

**Comment by inco-cc** [comment]
have you tried other standard pinentry programs like `pinentry-gtk-2`, `pinentry-gnome` etc? if those don't work either, then I'm afraid I'm out of ideas...

**Comment by BachoSeven** [comment]
The standard graphical gtk2 pinentry works for sure. I don't know why your program won't, the only thing which comes to mind is my dmenu which is heavily patched. I will try with a clean version with only the passwd patch on it and let you know.

**Comment by inco-cc** [comment]
it's been about a week now since your last response, so I'll close this issue for the time being. but feel free to re-open if you find a lead on this thing that could be related to this script. best of luck!
